name: Patch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  Patch:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 💾 Cache node_modules
        uses: actions/cache@v5
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: ✨ Initialize package.json if not exists
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi

      - name: 🕒 Decide version bump type
        run: |
          TODAY=$(date -u +"%Y-%m")
          FILE=".version-date"

          if [ ! -f "$FILE" ]; then
            echo -n "$TODAY" > $FILE
          fi

          LAST=$(cat $FILE)

          if [ "$TODAY" != "$LAST" ]; then
            npm version minor --no-git-tag-version
            echo -n "$TODAY" > $FILE
          else
            npm version patch --no-git-tag-version            
          fi

      - name: 🛠️ Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: ⬇️ Pull latest changes to avoid conflicts
        run: |
          git fetch
          git pull

      - name: 📤 Commit changes if needed
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update version"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
