name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  Prettier:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 💾 Cache node_modules
        uses: actions/cache@v5
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: ✨ Initialize package.json if not exists
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi

      - name: 📦 Install Prettier
        run: npm install --save-dev prettier

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: 📝 Create configuration
        run: |
          if [ ! -f .prettierrc.json ]; then
            if [ -f .prettierrc ]; then
              mv .prettierrc .prettierrc.json            
            fi        
            if [ ! -f .prettierrc.json ]; then
              echo '{"semi": true, "singleQuote": true, "tabWidth": 2, "printWidth": 80, "trailingComma": "es5", "bracketSpacing": true, "arrowParens": "avoid", "proseWrap": "never"}' > .prettierrc.json
            fi
          fi

      - name: ✍️ Run Prettier fix
        run: npx prettier --write .

      - name: 🛠️ Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 📤 Commit changes if needed
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Apply formatting ESLint"
            git pull
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
